apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: prestodb
  namespace: presto
spec:
  generateBucketName: prestodb
  storageClassName: openshift-storage.ceph.rook.io
  additionalConfig:
    ANY_KEY: VALUE
