apiVersion: starburstdata.com/v1
kind: Presto
metadata:
  name: presto-ocs-demo
spec:
  nameOverride: presto-ocs-demo
  prometheus:
    enabled: true
    additionalRules:
      - pattern: 'presto.execution<name=TaskManager><>FailedTasks.TotalCount'
        name: 'failed_tasks'
        type: COUNTER
  service:
    type: NodePort
    name: example-presto
  memory:
    nodeMemoryHeadroom: 1Gi
  coordinator:
    cpuRequest: ""
    memoryAllocation: ""
  worker:
    count: 3
    prestoWorkerShutdownGracePeriodSeconds: 1
    cpuRequest: ""
    memoryAllocation: ""
  hive:
    awsSecretName: presto-s3
    additionalProperties: |
      connector.name=hive-hadoop2
      hive.s3.endpoint=http://rook-ceph-rgw-s3a.openshift-storage.svc.cluster.local
      hive.s3.signer-type=AWSS3V4SignerType
      hive.s3.path-style-access=true
      hive.s3.use-instance-credentials=false
      hive.s3.staging-directory=/tmp
      hive.s3.ssl.enabled=false
      hive.s3.sse.enabled=false
      hive.s3.max-connections=100
    internalMetastore:
      s3Endpoint: http://rook-ceph-rgw-s3a.openshift-storage.svc.cluster.local
      image:
        imagepullPolicy: IfNotPresent
      memory: 0.5G
      cpu: 0.5
      postgreSql:
        jdbcUrl: jdbc:postgresql://postgresql.presto.svc.cluster.local/redhat
        username: redhat
        password: redhat
  additionalCatalogs:
    tpcds: |
      connector.name=tpcds
    postgresql: |
      connector.name=postgresql
      connection-url=jdbc:postgresql://postgresql.presto.svc.cluster.local/redhat
      connection-user=redhat
      connection-password=redhat
